apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-gcpnschf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-gcpnschf 
  name: python-gcpnschf
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-gcpnschf 
